### ISSUE TITLE
[Bug] Incompatibility with "Charm"

### ISSUE THREAD

**Issue by SylisMC** [Azagwen/ATBYW#14]
**Versions**
* Charm version - charm-fabric-1.16.4-2.2.0` (latest release offed in [issue 442](https://github.com/svenhjol/Charm/issues/442))
* ATBYW version - atbyw-1.16.4-1.3.4
* Minecraft version - 1.16.4`

**Description**
Bootup crash when loading with [All The Blocks You Want](https://www.curseforge.com/minecraft/mc-mods/atbyw) With [Charm](https://www.curseforge.com/minecraft/mc-mods/charm)
(crash before Mojang loading screen)
[latest.log](https://github.com/svenhjol/Charm/files/5742424/latest.log)

Also Uploaded on other mods issue tracker [HERE](https://github.com/svenhjol/Charm/issues/448)

**Comment by Azagwen** [comment]
This has been reported day 1 when I released the mod, I still don't really know how I could fix it without breaking my mod...

**Comment by Azagwen** [comment]
it seems Charm's [EnchantingTableBlockMixin](https://github.com/svenhjol/Charm/blob/master/src/main/java/svenhjol/charm/mixin/EnchantingTableBlockMixin.java) and ATBYW's [EnchantingTableBlockMixin](https://github.com/Azagwen/ATBYW/blob/master/src/main/java/net/azagwen/atbyw/mixin/EnchantingTableBlockMixin.java) are trying to mixin into the same part of the same class.

Which causes the game to crash on startup. also referrenced in #2

**Comment by SylisMC** [comment]
My bad, I checked the charm page first and didn't see a report there and created this post after already creating the charm post.

would an option in the config file to completely remove the enchanting table related content resolve the issue?

**Comment by SylisMC** [comment]
For the time being, I came up with the best workaround my coder illiterate brain could muster, expanding off of your suggestion from [Issue #2](https://github.com/Azagwen/ATBYW/issues/2)

Charm and ATBYW Both add nearly the variant bookshelves. however, you took it a step further with the Redstone bookshelves, Charm also has a config to disable every aspect of the mod so for now...

1) Remove "EnchantingTableBlockMixin" From charms mod file
2) Set `"VariantBookshelves Enabled" = false` in the charm config
3) Set `"VariantLadders Enabled" = false` being that both mods add them (ATBYW also adds bamboo)

**Comment by Azagwen** [comment]
> For the time being, I came up with the best workaround my coder illiterate brain could muster, expanding off of your suggestion from [Issue #2](https://github.com/Azagwen/ATBYW/issues/2)
> 
> Charm and ATBYW Both add nearly the variant bookshelves. however, you took it a step further with the Redstone bookshelves, Charm also has a config to disable every aspect of the mod so for now...
> 
> 1. Remove "EnchantingTableBlockMixin" From charms mod file
> 2. Set `"VariantBookshelves Enabled" = false` in the charm config
> 3. Set `"VariantLadders Enabled" = false` being that both mods add them (ATBYW also adds bamboo)

Yeah the best workaround to avoid crash on startup so far is to disable either of the two mods `EnchantingTableBlockMixin`. The ladders might also cause some recipe interferences but I didn't get to test that, thanks for mentioning it.

**Comment by SylisMC** [comment]
Charm resolved this issue with their latest update, it also resolves an issue with charm and better end having the same problem so the 3 mods should work fine together now
https://github.com/svenhjol/Charm/issues/448

**Comment by Azagwen** [comment]
Alright, I saw it when they added it to the source, I was just waiting for it to be released fully
