### ISSUE TITLE
When ATBYW is installed you can't use modded planks to craft sticks

### ISSUE THREAD

**Issue by toktoktheeo** [Azagwen/ATBYW#16]
Hi, 

I just found out that when ATBYW is installed, you can't use the planks of modded woods to craft sticks. You can only use the vanilla  planks.

I have Better Nether, Better End, Oh The Biomes You'll Go, Cinderscape, Terrestria, and Traverse installed.

Maybe there are other bad interractions like that.

Have a nice day.

**Comment by Azagwen** [comment]
I still have to look into dependencies, I had actually thought about adding those but I don't know how I could do it best. thanks for reminding me !
