### ISSUE TITLE
[Suggestion] Granite, Andesite, Diorite - Bricks, Bricks slabs, Walls

### ISSUE THREAD

**Issue by K0-RR** [Azagwen/ATBYW#17]
Some images 
![image](https://user-images.githubusercontent.com/43277609/103168511-10114a80-4834-11eb-9eb1-9b1b3e9be903.png)
![image](https://user-images.githubusercontent.com/43277609/103168469-c58fce00-4833-11eb-9ae0-7057c04d401e.png)
![image](https://user-images.githubusercontent.com/43277609/103168475-cfb1cc80-4833-11eb-96aa-d807d8b3eb35.png)
![image](https://user-images.githubusercontent.com/43277609/103168479-d9d3cb00-4833-11eb-9e02-f62610388081.png)
![image](https://user-images.githubusercontent.com/43277609/103168488-e6582380-4833-11eb-93a9-5deb68badede.png)
![image](https://user-images.githubusercontent.com/43277609/103168492-ece69b00-4833-11eb-8f25-7a4554509bf3.png)

**Comment by Azagwen** [comment]
Those were considered when I started making the mod but wasn't added, it's still in my ideas box tho.

**Comment by Azagwen** [comment]
Granite, Diorite and Andesite related blocks have been added, including bricks, stairs and slabs as well as columns.
No walls unfortunately, as I thought they'd be too much with what we already have, but who knows, maybe later !

Closing this for now, thanks for the suggestion !
