### ISSUE TITLE
Crash on Startup - Interference with "Charms"

### ISSUE THREAD

**Issue by Tetrajak** [Azagwen/ATBYW#2]
MC Version: 1.16.4
Fabric Version: 0.10.8
Java Version: 1.8.0_271, 64-bit
Launcher: MultiMC 5

As per the title, with the mod installed the game fails to launch, but without it the instance launches just fine.

Crash log: https://pastebin.com/pMW1paWh

**Comment by Azagwen** [comment]
It seems like "charm" interferes with my mod, because it also modifies how the Enchanting table works.
I don't really know how to deal with this kind of interference issue yet but be sure I'll gather info on how to do so !

**Comment by Tetrajak** [comment]
I can confirm the game launches if Charm is removed.

**Comment by Azagwen** [comment]
> I can confirm the game launches if Charm is removed.

Temporary fix I can suggest is to dig into my mod's jar and edit "atbyw.mixins.json" to remove "EnchantingTableBlockMixin" fron "client" mixins.
If it still doesn't launch after that edit feel free to come back to me with the new log.

**Comment by RDKRACZ** [comment]
I removed "EnchantingTableBlockMixin" and the game can now launch with both mods.

**Comment by SylisMC** [comment]
> I removed "EnchantingTableBlockMixin" and the game can now launch with both mods.

I found a better fix.
Charm and ATBYW both add bookshelves, exact same blocks, exact same recipes, However, ATBYW also adds Redstone bookshelves. also, charm has a diverse config and ATBYW doesnt have a config file yet. so.

1) Remove "EnchantingTableBlockMixin" From charms mod file
2) Set `"VariantBookshelves Enabled" = false` in the charm config
3) set `"VariantLadders Enabled" = false` being that both mods add them (ATBYW also adds bamboo)
