### ISSUE TITLE
Can't craft from atbyw stick variants.

### ISSUE THREAD

**Issue by K0-RR** [Azagwen/ATBYW#24]

**Comment by Azagwen** [comment]
More information needed

**Comment by K0-RR** [comment]
It is valid. I will explain more clearly when I go back home today.

**Comment by RDKRACZ** [comment]
![2021-02-01_19 34 46](https://user-images.githubusercontent.com/43277609/106502653-ea2b3580-64c4-11eb-9f9b-ba07d2dbeb4f.png)

**Comment by K0-RR** [comment]
![2021-02-01_19 39 45](https://user-images.githubusercontent.com/43277609/106502989-658ce700-64c5-11eb-8800-7e19a19e0ab8.png)
![2021-02-01_19 39 57](https://user-images.githubusercontent.com/43277609/106502990-66257d80-64c5-11eb-89fc-643e640e0d82.png)

**Comment by Azagwen** [comment]
I have already fixed that, what version are you using ?

EDIT : it was actually already included in the release that added more sticks

**Comment by Azagwen** [comment]
I had some time to test this in the latest release, no issue at all.

Again this possibility was implemented alongside stick variants so it has no reason to not work, will re-open only if proper info is given (e.g. do you have other mods installed, what release are you using that this issue occurs in, etc..)
