### ISSUE TITLE
[Feature request] Possibility to use bamboo sticks like sticks in crafting recipes for torches, tools etc. 

### ISSUE THREAD

**Issue by K0-RR** [Azagwen/ATBYW#25]

**Comment by Azagwen** [comment]
this is already possible. please check what version you play on, and are there other mods installed

**Comment by K0-RR** [comment]
> this is already possible

No. I'm using the latest release - 1.3.4
![image](https://user-images.githubusercontent.com/43277609/111053318-2b6b1980-8463-11eb-88be-50820a5dbab7.png)
