### ISSUE TITLE
A solution for ATBYW having 3 tabs in the creative inventory.

### ISSUE THREAD

**Issue by K0-RR** [Azagwen/ATBYW#27]
Please read https://github.com/Noaaan/MythicMetals/issues/30

**Comment by Azagwen** [comment]
## `Fixed in dev code` 😳

![image](https://user-images.githubusercontent.com/30528331/116616635-3576a800-a93d-11eb-9d39-b42cb9e5879d.png)

**Comment by K0-RR** [comment]
Whoa, nice! Someone has really done it (I reported this to a few other devs when it was needed and you are the first who did it).

**Comment by Azagwen** [comment]
> Whoa, nice! Someone has really done it (I reported this to a few other devs when it was needed and you are the first who did it).

I thought it was a neat idea ! I know from a long experience playing with mods that creative tabs can tend to fill the creative inventory with hundreds of pages. So having my tabs merged into one should contribute a little to fixing this issue :D

Wish the others luck implementing it, Gui and inventory code isn't always fun.
