### ISSUE TITLE
consider moving or deleting "curseforge" assets folder

### ISSUE THREAD

**Issue by oliwoli** [Azagwen/ATBYW#29]
When building your mod, the curseforge folder gets included in the final jar file which ends up being massive (138MB).

I'd consider moving the folder (or actually deleting it). Also you could reduce the file size by compressing the gif- and removing psd files ("crafting_table_cycling_recipes.psd" is 56Mb).

**Comment by Azagwen** [comment]
good call, I'll make sure to remove it from the release, considering it's only for my own use.
