### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by Soochaehwa** [Azagwen/ATBYW#33]
[latest.log](https://github.com/Azagwen/ATBYW/files/6680939/latest.log)

It seems that the ItemModelLoaderMixin is not loading from the server

**Comment by Azagwen** [comment]
in the mod JAR there should be a file called `atbyw.mixins.json`.
Open it and move `ItemModelLoaderMixin` to the `client` list.

it should fix this

I'll fix it on my end for the next release 👍 

EDIT : `TexturedRenderLayersMixin` can also be moved to client side just to be safe

**Comment by Azagwen** [comment]
a small Patch fixing this should come out on curseforge shortly (once it's approved)
