### ISSUE TITLE
world wont load when you reload a world

### ISSUE THREAD

**Issue by TheNimbleNinja** [Azagwen/ATBYW#36]
It seems atbyw:ice_spike_base | atbyw:ice_spike_base is the cause because it is not added 
 to the FlatChunkGeneratorConfig.STRUCTURE_FEATURE map. Please let the mod owner 
 of that structure know about this crash. That way they can add their structure 
 to that map since someone is trying to spawn it in a flat/custom dimension. 
 
was wat was in the log

**Comment by Azagwen** [comment]
Could you give me more info? What mod is this log from, I don't get this error on my end.
