### ISSUE TITLE
1.16.4-1.2.4 Bookshelves do not increase enchanting table enchantment level while installed alongside BetterEnd

### ISSUE THREAD

**Issue by NotAVerb** [Azagwen/ATBYW#6]
The bookshelves added by the mod do actually create the glyph particles when they're near enchanting tables, but they have no effect on enchantment mechanics.

**Comment by NotAVerb** [comment]
On further testing this actually seems to be a minor mod incompatibility with BetterEnd. BetterEnd adds bookshelves for its added wood types. However with both ATBYW and BetterEnd installed, only the BetterEnd bookshelves contribute enchanting levels.

**Comment by Azagwen** [comment]
I'll look into it !

**Comment by Azagwen** [comment]
Managed to fix it, it will be added to the next release.

This issue will be closed once it's published.
