### ISSUE TITLE
More fence door variants and features.

### ISSUE THREAD

**Issue by RDKRACZ** [Azagwen/ATBYW#7]
Mods: Cinderscapes, BYG, Terrestria, Traverse, Wild Explorer are adding more wood types and doors from them. Can You add these doors in "fence" type? BTW I love these fence doors. I understand they are placed like a fence - in the middle of the block - but can it be possible to place them like a normal doors, on the block edge?

**Comment by Azagwen** [comment]
The purpose of Fence Doors is to be used with walls and fences, as they connect to those.

As for the wood types, I'll look into it !
