### ISSUE TITLE
More concrete blocks 

### ISSUE THREAD

**Issue by RDKRACZ** [Azagwen/ATBYW#8]
Your Mod adds a few things from Terracotta:
_Terracotta Stairs
Terracotta Slabs
Terracotta Bricks
Terracotta Bricks Stairs
Terracotta Bricks Slabs
Terracotta Bricks Wall_

Could You add the same blocks but from concrete?

**Comment by Azagwen** [comment]
This was actually planned in the first release, but Terracotta variants took me so long to make data and assets for that I didn't add Concrete variants
